development:
  user: 'staging'
  password: 'staging'
  host: '200.143.198.46'
  port: 8886
  callback_url: 'http://localhost:3000/conteudos/granularizou'
  callback_verb: 'POST'

test:
  user: 'staging'
  password: 'staging'
  host: '200.143.198.46'
  port: 8886
  callback_url: 'http://localhost:3000/conteudos/granularizou'
  callback_verb: 'POST'
